# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.31)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::Core)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::Core
add_library(Qt6::Core SHARED IMPORTED)

set_target_properties(Qt6::Core PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION;QT_COORD_TYPE"
  INTERFACE_COMPILE_DEFINITIONS "QT_CORE_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/include;/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/include/QtCore"
  INTERFACE_LINK_LIBRARIES "Qt6::Platform;WrapAtomic::WrapAtomic"
  INTERFACE_QT_COORD_TYPE "double"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/src/corelib/meta_types/qt6core_metatypes.json>"
  QT_DISABLED_PRIVATE_FEATURES "copy_file_range;system_doubleconversion;broken_threadlocal_dtors;getauxval;glib;icu;winsdkicu;windows_ioring;windows_ioring_skip_builder_param_checks;inotify;jemalloc;journald;system_libb2;linkat;liburing;system_pcre2;poll_ppoll;poll_pollts;poll_select;posix_sem;pthread_clockjoin;pthread_condattr_setclock;pthread_timedjoin;qqnx_pps;renameat2;slog2;syslog;sysv_sem;sysv_shm;vxpipedrv;backtrace;cxx23_stacktrace;cpp_winrt;timezone_locale;lttng;etw;ctf;forkfd_pidfd;poll_exit_on_error;openssl_hash;async_io;use_bfd_linker;use_gold_linker;use_lld_linker;use_mold_linker;android_style_assets;gc_binaries;debug;elf_private_full_version;no_direct_extern_access;x86intrin;sse2;sse3;ssse3;sse4_1;sse4_2;avx;f16c;avx2;avx512f;avx512er;avx512cd;avx512pf;avx512dq;avx512bw;avx512vl;avx512ifma;avx512vbmi;avx512vbmi2;aesni;vaes;rdrnd;rdseed;shani;lsx;lasx;mips_dsp;mips_dspr2;neon;arm_crc32;arm_crypto;arm_sve;localtime_s;force_system_libs;force_bundled_libs;system_zlib;stdlib_libcpp;dbus;dbus_linked;libudev;openssl;intelcet;glibc_fortify_source;stack_protector;stack_clash_protection;libstdcpp_assertions;relro_now_linker;android_16kb_pages"
  QT_DISABLED_PUBLIC_FEATURES "glib;inotify;jemalloc;systemsemaphore;cpp_winrt;process;timezone;timezone_tzdb;static;pkg_config;debug_and_release;separate_debug_info;appstore_compliant;simulator_and_device;force_asserts;framework;cxx20;cxx2a;cxx2b;cxx2c;reduce_relocations;wasm_simd128;wasm_exceptions;wasm_jspi;zstd;thread;dbus;openssl_linked;opensslv11;opensslv30"
  QT_ENABLED_PRIVATE_FEATURES "clock_gettime;doubleconversion;dladdr;futimens;getentropy;memmem;memrchr;mimetype_database;poll_poll;posix_shm;dup3;accept4;cxx20_format;sha3_fast;hijricalendar;datetimeparser;pcre2;developer_build;private_tests;doc_snippets;reduce_exports;localtime_r;posix_fallocate;gui;network;printsupport;sql;testlib;widgets;xml;dlopen;relocatable;trivial_auto_var_init_pattern;libcpp_hardening;cross_compile;largefile"
  QT_ENABLED_PUBLIC_FEATURES "clock_monotonic;cxx11_future;cxx17_filesystem;std_atomic64;mimetype;regularexpression;sharedmemory;shortcut;xmlstream;xmlstreamreader;xmlstreamwriter;textdate;datestring;processenvironment;temporaryfile;library;settings;filesystemwatcher;filesystemiterator;itemmodel;proxymodel;sortfilterproxymodel;identityproxymodel;transposeproxymodel;concatenatetablesproxymodel;stringlistmodel;translation;easingcurve;animation;gestures;jalalicalendar;islamiccivilcalendar;commandlineparser;cborstreamreader;cborstreamwriter;permissions;threadsafe_cloexec;version_tagging;shared;cross_compile;rpath;signaling_nan;future;concurrent;test_gui;test_squish;shared;cross_compile;plugin_manifest;trivial_auto_var_init_pattern;libcpp_hardening;shared;no_pkg_config;private_tests;rpath;reduce_exports"
  QT_QMAKE_PRIVATE_CONFIG "pcre2;cross_compile;largefile"
  QT_QMAKE_PUBLIC_CONFIG "shared;cross_compile;plugin_manifest;trivial_auto_var_init_pattern;libcpp_hardening"
  QT_QMAKE_PUBLIC_QT_CONFIG "threadsafe_cloexec;shared;no_pkg_config;private_tests;rpath;reduce_exports"
  _qt_config_module_name "core"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_has_public_headers "TRUE"
  _qt_module_include_name "QtCore"
  _qt_module_interface_name "Core"
  _qt_module_relative_include_dir "../../../include/QtCore"
  _qt_package_name "Qt6Core"
  _qt_package_version "6.11.1"
  _qt_private_module_target_name "CorePrivate"
)

# Import target "Qt6::Core" for configuration "Release"
set_property(TARGET Qt6::Core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::Core PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/lib/libQt6Core.so"
  IMPORTED_SONAME_RELEASE "libQt6Core.so"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::Platform" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
