# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.31)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::qmlwavefrontmeshplugin)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::qmlwavefrontmeshplugin
add_library(Qt6::qmlwavefrontmeshplugin MODULE IMPORTED)

set_target_properties(Qt6::qmlwavefrontmeshplugin PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtdeclarative/src/labs/wavefrontmesh/meta_types/qt6labswavefrontmesh_metatypes.json>"
  QT_DEFAULT_PLUGIN "0"
  QT_PLUGIN_CLASS_NAME "QmlWavefrontMeshPlugin"
  QT_PLUGIN_TYPE "qml_plugin"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_qml_backing_library_and_plugin_are_same_target "FALSE"
  _qt_qml_module_backing_target "LabsWavefrontMesh"
  _qt_qml_module_class_name "QmlWavefrontMeshPlugin"
  _qt_qml_module_is_plugin_target "TRUE"
  _qt_qml_module_plugin_has_backing_library "TRUE"
  _qt_qml_module_target_path "Qt/labs/wavefrontmesh"
  _qt_qml_module_uri "Qt.labs.wavefrontmesh"
  _qt_qml_module_version "6.11"
)

# Import target "Qt6::qmlwavefrontmeshplugin" for configuration "Release"
set_property(TARGET Qt6::qmlwavefrontmeshplugin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmlwavefrontmeshplugin PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELEASE ""
  IMPORTED_LOCATION_RELEASE "/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/qml/Qt/labs/wavefrontmesh/libqmlwavefrontmeshplugin.so"
  IMPORTED_NO_SONAME_RELEASE "TRUE"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
