# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.31)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::MultimediaTestLibPrivate)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::MultimediaTestLibPrivate
add_library(Qt6::MultimediaTestLibPrivate STATIC IMPORTED)

set_target_properties(Qt6::MultimediaTestLibPrivate PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_MULTIMEDIATESTLIBPRIVATE_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/include;/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/include/QtMultimediaTestLib;/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtmultimedia/src/multimediatestlib;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::MultimediaTestLibPrivate,_qt_module_has_private_headers>>:/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/include/QtMultimediaTestLib/6.11.1>;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::MultimediaTestLibPrivate,_qt_module_has_private_headers>>:/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/include/QtMultimediaTestLib/6.11.1/QtMultimediaTestLib>;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::MultimediaTestLibPrivate,_qt_module_has_private_headers>>:>;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::MultimediaTestLibPrivate,_qt_module_has_private_headers>>:>"
  INTERFACE_LINK_LIBRARIES "Qt6::Core;Qt6::CorePrivate;Qt6::Gui;Qt6::GuiPrivate;Qt6::Multimedia;Qt6::MultimediaPrivate;Qt6::Test;\$<LINK_ONLY:Qt6::PlatformModuleInternal>"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtmultimedia/src/multimediatestlib/meta_types/qt6multimediatestlibprivate_metatypes.json>"
  _qt_config_module_name "multimediatestlibprivate_private"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_module "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_include_name "QtMultimediaTestLib"
  _qt_module_interface_name "MultimediaTestLib"
  _qt_module_relative_include_dir "../../../include/QtMultimediaTestLib"
  _qt_package_name "Qt6MultimediaTestLibPrivate"
  _qt_package_version "6.11.1"
)

# Import target "Qt6::MultimediaTestLibPrivate" for configuration "Release"
set_property(TARGET Qt6::MultimediaTestLibPrivate APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::MultimediaTestLibPrivate PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/lib/libQt6MultimediaTestLib.a"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::Core" "Qt6::CorePrivate" "Qt6::Gui" "Qt6::GuiPrivate" "Qt6::Multimedia" "Qt6::MultimediaPrivate" "Qt6::Test" "Qt6::PlatformModuleInternal" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
