# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.31)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::Qml)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::Qml
add_library(Qt6::Qml SHARED IMPORTED)

set_target_properties(Qt6::Qml PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_QML_LIB;\$<\$<AND:\$<STREQUAL:\$<TARGET_PROPERTY:TYPE>,EXECUTABLE>,\$<BOOL:\$<TARGET_PROPERTY:QT_ENABLE_QML_DEBUG>>>:QT_QML_DEBUG>"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/include;/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/include/QtQml"
  INTERFACE_LINK_LIBRARIES "Qt6::Core;Qt6::QmlIntegration;Qt6::Network"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtdeclarative/src/qml/meta_types/qt6qml_metatypes.json>"
  MODULE_PLUGIN_TYPES "qmltooling"
  QT_DISABLED_PRIVATE_FEATURES "qml_jit;qml_profiler;qml_preview;qml_worker_script;qml_type_loader_thread"
  QT_DISABLED_PUBLIC_FEATURES "qml_ssl"
  QT_ENABLED_PRIVATE_FEATURES "qml_xml_http_request;qml_locale;qml_animation;qml_itemmodel;qml_xmllistmodel;qml_python;qmlcontextpropertydump"
  QT_ENABLED_PUBLIC_FEATURES "qml_network;qml_debug;qml_labs"
  QT_QMAKE_PRIVATE_CONFIG ""
  QT_QMAKE_PUBLIC_CONFIG ""
  QT_QMAKE_PUBLIC_QT_CONFIG ""
  TRANSITIVE_COMPILE_PROPERTIES "QT_PLUGIN_TARGETS"
  _qt_config_module_name "qml"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_has_public_headers "TRUE"
  _qt_module_include_name "QtQml"
  _qt_module_interface_name "Qml"
  _qt_module_relative_include_dir "../../../include/QtQml"
  _qt_package_name "Qt6Qml"
  _qt_package_version "6.11.1"
  _qt_private_module_target_name "QmlPrivate"
  _qt_qml_backing_library_and_plugin_are_same_target "FALSE"
  _qt_qml_module_class_name "QMLPlugin"
  _qt_qml_module_has_plugin "FALSE"
  _qt_qml_module_installed_plugin_target ""
  _qt_qml_module_installed_qmldir_path "qml/QML/qmldir"
  _qt_qml_module_is_backing_target "TRUE"
  _qt_qml_module_plugin_target ""
  _qt_qml_module_target_path "QML"
  _qt_qml_module_uri "QML"
  _qt_qml_module_version "1.0"
)

# Import target "Qt6::Qml" for configuration "Release"
set_property(TARGET Qt6::Qml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::Qml PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/lib/libQt6Qml.so"
  IMPORTED_SONAME_RELEASE "libQt6Qml.so"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::Core" "Qt6::QmlIntegration" "Qt6::Network" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
