# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.31)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::QuickControls2FluentWinUI3StyleImpl)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::QuickControls2FluentWinUI3StyleImpl
add_library(Qt6::QuickControls2FluentWinUI3StyleImpl SHARED IMPORTED)

set_target_properties(Qt6::QuickControls2FluentWinUI3StyleImpl PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_QUICKCONTROLS2FLUENTWINUI3STYLEIMPL_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/include;/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/include/QtQuickControls2FluentWinUI3StyleImpl"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtdeclarative/src/quickcontrols/fluentwinui3/impl/meta_types/qt6quickcontrols2fluentwinui3styleimpl_metatypes.json>"
  _qt_config_module_name "quickcontrols2fluentwinui3styleimpl"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_has_public_headers "TRUE"
  _qt_module_include_name "QtQuickControls2FluentWinUI3StyleImpl"
  _qt_module_interface_name "QuickControls2FluentWinUI3StyleImpl"
  _qt_module_relative_include_dir "../../../include/QtQuickControls2FluentWinUI3StyleImpl"
  _qt_package_name "Qt6QuickControls2FluentWinUI3StyleImpl"
  _qt_package_version "6.11.1"
  _qt_private_module_target_name "QuickControls2FluentWinUI3StyleImplPrivate"
  _qt_qml_backing_library_and_plugin_are_same_target "FALSE"
  _qt_qml_module_class_name "QtQuickControls2FluentWinUI3StyleImplPlugin"
  _qt_qml_module_has_plugin "TRUE"
  _qt_qml_module_installed_plugin_target "Qt6::qtquickcontrols2fluentwinui3styleimplplugin"
  _qt_qml_module_installed_qmldir_path "qml/QtQuick/Controls/FluentWinUI3/impl/qmldir"
  _qt_qml_module_is_backing_target "TRUE"
  _qt_qml_module_plugin_target "qtquickcontrols2fluentwinui3styleimplplugin"
  _qt_qml_module_target_path "QtQuick/Controls/FluentWinUI3/impl"
  _qt_qml_module_uri "QtQuick.Controls.FluentWinUI3.impl"
  _qt_qml_module_version "6.11"
)

# Import target "Qt6::QuickControls2FluentWinUI3StyleImpl" for configuration "Release"
set_property(TARGET Qt6::QuickControls2FluentWinUI3StyleImpl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::QuickControls2FluentWinUI3StyleImpl PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "Qt6::Core;Qt6::Gui;Qt6::Qml;Qt6::Quick;Qt6::QuickTemplates2"
  IMPORTED_LOCATION_RELEASE "/Users/msorvig/code/qmlplayground/qt/wasm-shared/qtbase/lib/libQt6QuickControls2FluentWinUI3StyleImpl.so"
  IMPORTED_SONAME_RELEASE "libQt6QuickControls2FluentWinUI3StyleImpl.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
